deepspeed --include localhost:0,1,2,3 ./train_lora_out_len.py \
  --model_name_or_path /workspace/Sequence-Scheduling/ckpts/vicuna-7b \
  --lora_r 8 \
  --lora_alpha 16 \
  --lora_dropout 0.05 \
  --data_path /workspace/Sequence-Scheduling/data/alpaca-train-10k-instruct.json \
  --bf16 False \
  --output_dir /workspace/Sequence-Scheduling/ckpts/vicuna-response-length-perception-module \
  --num_train_epochs 1 \
  --per_device_train_batch_size 4 \
  --per_device_eval_batch_size 4 \
  --gradient_accumulation_steps 1 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 1200 \
  --save_total_limit 5 \
  --learning_rate 5e-4 \
  --weight_decay 0. \
  --warmup_ratio 0.03 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --tf32 False \
  --model_max_length 256 \
  --deepspeed ../deepspeed-config.json \
  --report_to none
